### ISSUE TITLE
minimap for editing mode

### ISSUE THREAD

**Issue by sublimeclemency** [lumetrium/obsidian-teleprompter#8]
editors often have a minimap that acts like a scrollbar, in parallel with the editor itself.

![minimap](https://github.com/lumetrium/obsidian-teleprompter/assets/124845026/7668d2a2-3959-4bc5-be59-fc81744e6824)

please make it possible for the teleprompter preview to act as a minimap that controls the obsidian editor!

**Comment by lumetrium** [comment]
Thank you for your suggestion, but the ability to control the editor goes beyond the intended scope of this plugin's functionality. This plugin interacts with the editor solely by monitoring changes and then updating the content in the teleprompter window accordingly. Minimap for the editor would be more suitable for a separate, standalone plugin, rather than being integrated into the teleprompter's functionality.
